### ISSUE TITLE
Some setup issues

### ISSUE THREAD

**Issue by hsinhaoHHuang** [ChunYen-Chen/CheckNode#1]
1. When I reinstalled, it doesn't source `.bashrc` after running `setup.sh`.

1. When running `node`  outside the `CheckNode/`, there is a error:
`sed: can't read config: No such file or directory`

1. Also, it will create `now_*` in the current directory, not in `CheckNode/`

**Comment by ChunYen-Chen** [comment]
Thanks for the bug report!
1. It seems like I can not use the command `source` in the shell script, so I separate this part to another step of setup.
2. & 3. I fix the directory bugs.  Please update your code to the latest version to fix this issue.
